site_name: Datero Docs
site_url: https://datero.tech/docs/
repo_url: https://github.com/chumaky/datero-docs
site_description: Datero data platform documentation
site_author: Chumaky IT
theme:
  name: material
  features:
  #- header.autohide
  #- navigation.tabs
  - navigation.instant
  #- navigation.sections
  - navigation.tracking
  - navigation.indexes
  - navigation.top
  - navigation.path
  - navigation.footer
  # this options switches off "Table of Contents" section on the right side
  #- toc.integrate
  #- toc.follow
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  language: en
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: teal
    accent: light blue
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime

extra_css:
  - stylesheets/extra.css

markdown_extensions:
# Python Markdown
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true
- tables
# Python Markdown Extensions
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.snippets:
    auto_append:
      - include/abbreviations.md
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde


plugins:
- search
- glightbox
- table-reader


nav:
- Home: index.md
- Overview: overview.md
- Installation: installation.md
- Tutorial: tutorial.md
- Connectors:
  - connectors/index.md
  - MySQL: connectors/mysql.md
  - Postgres: connectors/postgres.md
  - Mongo: connectors/mongo.md
  - Oracle: connectors/oracle.md
  - MSSQL: connectors/mssql.md
  - SQLite: connectors/sqlite.md
  - File: connectors/file.md
- GCP: clouds/gcp.md
