# for list of available options see "default.yaml" and "schema.yaml"

# section placeholders to override default values
postgres:
  port: 4444
  username: datero
  password: datero

fdw_list:

servers:
  mysql_fdw_1:
    description: MyProject - dev
    fdw_name: mysql_fdw
    options:
      host: mysql
      port: 3306
    user_mapping:
      username: test
      password: test
    import_foreign_schema:
      remote_schema: dev
      local_schema: mysql

  oracle_fdw_1:
    description: Another project - PRD
    fdw_name: oracle_fdw
    options:
      dbserver: //oracle:1521/xepdb1
    user_mapping:
      user: test
      password: test
    import_foreign_schema:
      remote_schema: TEST
      local_schema: oracle

