services:
  # --8<-- [start:datero]
  datero:
    image: docker.io/chumaky/datero_engine:latest
    container_name: datero_main
    environment:
      POSTGRES_USER: datero
      POSTGRES_PASSWORD: datero
    ports:
      - 4444:5432
    volumes:
      - ./sqlite.db:/home/job_roles.db
      - /../data/tutorial/departments.csv:/home/departments.csv
  # --8<-- [end:datero]

  # --8<-- [start:mysql]
  mysql:
    image: docker.io/library/mysql:latest
    container_name: datero_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./mysql_setup.sql:/docker-entrypoint-initdb.d/mysql_setup.sql
  # --8<-- [end:mysql]

  # --8<-- [start:postgres]
  postgres:
    image: docker.io/library/postgres:alpine
    container_name: datero_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_setup.sql:/docker-entrypoint-initdb.d/postgres_setup.sql
  # --8<-- [end:postgres]

  # --8<-- [start:mongo]
  mongo:
    image: docker.io/library/mongo:latest
    container_name: datero_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - ./mongo_setup.js:/docker-entrypoint-initdb.d/mongo_setup.js
  # --8<-- [end:mongo]

  # --8<-- [start:mssql]
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: datero_mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: mssql_2019
    ports:
      - 1433:1433
    entrypoint:
      - /usr/config/entrypoint.sh
    volumes:
      - ./mssql_entrypoint.sh:/usr/config/entrypoint.sh
      - ./mssql_configure_db.sh:/usr/config/configure-db.sh
      - ./mssql_setup.sql:/usr/config/setup.sql
  # --8<-- [end:mssql]

