name: Deploy docs
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.ref }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build the site
        run: mkdocs build

      - name: Prepare remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            rm -rf ${BASE_PATH}/docs_old
            mv ${BASE_PATH}/docs ${BASE_PATH}/docs_old
            mkdir ${BASE_PATH}/docs
        env:
          BASE_PATH: /home/toleg/team/datero

      - name: Deploy to remote server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          source: site/*
          target: /home/toleg/team/datero/docs
          strip_components: 1

      - name: Clean up the build
        if: always()
        run: rm -rf site
