name: Deploy docs to remote server

on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        default: dev
        type: string
      ARTIFACT:
        required: true
        default: docs.tar.gz
        type: string
      REMOTE_HOST:
        required: true
        type: string
      REMOTE_PORT:
        required: true
        type: number
      REMOTE_USER:
        required: true
        type: string
    secrets:
      REMOTE_SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.ENV_NAME }}

    steps:
    - name: Print environment
      run: |
        echo Artifact: ${{ inputs.ARTIFACT }}
        echo "Base path (env): ${{ env.BASE_PATH }}"
        echo "Base path (secrets): ${{ secrets.BASE_PATH }}"
        echo "Base path (vars): ${{ vars.BASE_PATH }}"

    - name: Download an artifact
      uses: actions/download-artifact@v4
      with:
        name: docs

    - name: List an artifact
      run: ls -l

    - name: Copy artifact to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.REMOTE_HOST }}
        username: ${{ inputs.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ inputs.REMOTE_PORT }}
        source: ${{ inputs.ARTIFACT }}
        target: ${{ vars.BASE_PATH }}

    - name: Deploy remote server
      uses: appleboy/ssh-action@v1.0.3
      env:
        DIST_TAR: ${{ inputs.ARTIFACT }}
        BASE_PATH: ${{ vars.BASE_PATH }}
      with:
        host: ${{ inputs.REMOTE_HOST }}
        username: ${{ inputs.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ inputs.REMOTE_PORT }}
        envs: DIST_TAR,BASE_PATH,SERVER_PATH,SERVER_OLD_PATH,SERVER_TMP_PATH
        script: |
          SERVER_PATH=${BASE_PATH}/docs
          SERVER_OLD_PATH=${BASE_PATH}/docs_old
          SERVER_TMP_PATH=${BASE_PATH}/docs_tmp

          mkdir -p $SERVER_PATH
          mkdir -p $SERVER_OLD_PATH
          mkdir -p $SERVER_TMP_PATH

          rsync -a --delete $SERVER_PATH/ $SERVER_OLD_PATH/
          tar -xzf $BASE_PATH/$DIST_TAR --strip-components=1 -C $SERVER_TMP_PATH
          rsync -a --delete $SERVER_TMP_PATH/ $SERVER_PATH/

          rm -rf $SERVER_TMP_PATH
          rm -f $BASE_PATH/$DIST_TAR

